variables:
  MAVEN_OPTS: >-
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

.test: &test
  stage: test
  script:
    - mvn -B -V -e -P foss-parent-verification verify site site:stage
    - mv target/staging/${CI_PROJECT_NAME}/ target/staging/site
  except:
    - gh-pages

test:jdk7:3.3.9:
  <<: *test
  image: mfriedenhagen/docker-maven:3.3.9-jdk-7

test:jdk8:3.3.9:
  <<: *test
  image: mfriedenhagen/docker-maven:3.3.9-jdk-8
  artifacts:
    paths:
      - target/staging/site/

test:jdk8:3.4.0-SNAPSHOT:
  <<: *test
  image: mfriedenhagen/docker-maven:3.4.0-SNAPSHOT-jdk-8

test:jdk7:3.4.0-SNAPSHOT:
  <<: *test
  image: mfriedenhagen/docker-maven:3.4.0-SNAPSHOT-jdk-7

pages:
  image: busybox:latest
  stage: deploy
  script:
    - mv target/staging/site/ public
  dependencies:
    - test:jdk8:3.3.9
  artifacts:
    paths:
    - public
  only:
    - master

